spring:
  application:
    name: spring-cloud-stream-publisher

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  cloud:
    stream:
      bindings:
        employeeRegistration-out-0:
          destination: employee.registration.queue

        employeeRegistrationConsumer-in-0:
          destination: employee.registration.queue
